name: "Test and deploy"

on:
  push:
    branches: [ master ]

jobs:

  doc:
      - name: Build the Doc 🔧
        run: |
          cd docs
          make html
          touch build/html/.nojekyll
      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: docs/build/html/
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
